version: 2
updates:
  - package-ecosystem: "composer"
    schedule:
      interval: "weekly"
    groups:
      minor:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
