name: test

on:
  workflow_call:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@v3
        env:
          APP_ENV: dev
        with:
          php_version: 8.3
          path: 'src/'
      - uses: php-actions/phpunit@v4
        env:
          XDEBUG_MODE: coverage
        with:
          php_version: 8.3
          php_extensions: xdebug
          coverage_cobertura: coverage.cobertura.xml
          log_junit: report.xml
      - uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.cobertura.xml
      - uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
