name: test

on:
  workflow_call:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@v3
        env:
          APP_ENV: dev
        with:
          php_version: 8.3
          path: 'src/'
      - uses: php-actions/phpunit@v4
        env:
          XDEBUG_MODE: coverage
        with:
          php_version: 8.3
          php_extensions: xdebug
          coverage_clover: coverage.xml
          log_junit: report.xml
